# Generated by Django 4.1.10 on 2023-08-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_of_vacancie', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
    ]
