# Generated by Django 4.1.10 on 2023-08-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='conter_name',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='file_or_link',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='prefix',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='rubr_atrub',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='status',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='id_of_vacancie',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='name',
            field=models.TextField(default=None),
        ),
    ]
