# Generated by Django 4.1.10 on 2023-08-18 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_vacancies_conter_name_vacancies_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 8, 18, 14, 44, 18, 845270)),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='source',
            field=models.TextField(default='Ручной ввод'),
        ),
    ]
