# Generated by Django 4.1.10 on 2023-08-18 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_vacancies_data_vacancies_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='data',
        ),
        migrations.AddField(
            model_name='vacancies',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 18, 14, 46, 59, 432458)),
        ),
    ]
