# Generated by Django 4.1.10 on 2023-08-22 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_remove_vacancies_data_vacancies_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='category',
            field=models.TextField(default='Не указанно'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='contacts',
            field=models.TextField(default='Не указанно'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='zp',
            field=models.TextField(default='По договорённости'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
