# Generated by Django 4.1.10 on 2023-08-23 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_vacancies_category_vacancies_contacts_vacancies_zp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_seekers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_of_seekers', models.TextField(default=None)),
                ('fio', models.TextField(default='Вася Пупкин Анатольевич')),
                ('phone', models.TextField(default='+номер не ввёл уёбок')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('email', models.TextField(default='shit@govno.com')),
            ],
        ),
    ]
